### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by bigreni** [appfeel/admob-phonegap-build-demo#1]
Hi, 

I tried to run your demo using the steps you have given. I am building using phonegap v3.6.3. When I try to load the ads, I see the loading screen and then it vanishes and not ad is displayed.

I am using a Nexus 5 phone running Android lollipop. Any ideas?

Thanks

**Comment by appfeel** [comment]
Hi, I could not reproduce the issue. Meanwhile the plugin sdk version has been upgraded, could you try again?

Could you try to paste the logCat from eclipse?

Thanks

**Comment by appfeel** [comment]
Hi @bigreni, AdMob has blocked this package name to receive ads.

I'm already talking to them in order to fix it. Meanwhile you could try with changing the package name of the demo app in your eclipse project.
